
services:
  node-1:
    image: elasticsearch:8.10.2
    hostname: node-1
    environment:
      "node.name": "node-1"
      "network.host": "node-1"
      "discovery.seed_hosts": "node-2,node-3"
    volumes:
      # we need to mount the file instead of the dir to not overwrite other configs
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - storage-1:/var/data/elasticsearch:rw
      - log-1:/var/log/elasticsearch:rw
    ports:
      - "9200:9200"
    healthcheck: &def_health
      test: curl -sf 'http://localhost:9200/_cluster/health'
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy: &def_deploy
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 8G
      # restart_policy:
      #   condition: on-failure
      #   delay: 0s
      #   max_attempts: 3
      #   window: 120s

  node-2:
    image: elasticsearch:8.10.2
    hostname: node-2
    environment:
      "node.name": "node-2"
      "discovery.seed_hosts": "node-1,node-3"
    volumes:
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - storage-2:/var/data/elasticsearch:rw
      - log-2:/var/log/elasticsearch:rw
    ports:
      - "9201:9200"
    healthcheck: *def_health
    deploy: *def_deploy

  node-3:
    image: elasticsearch:8.10.2
    hostname: node-3
    environment:
      "node.name": "node-3"
      "network.host": "node-3"
      "discovery.seed_hosts": "node-1,node-2"
    volumes:
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - storage-3:/var/data/elasticsearch:rw
      - log-3:/var/log/elasticsearch:rw
    ports:
      - "9202:9200"
    healthcheck: *def_health
    deploy: *def_deploy

volumes:
  storage-1:
    name: elasticsearch-storage-1
    external: true
  storage-2:
    name: elasticsearch-storage-2
    external: true
  storage-3:
    name: elasticsearch-storage-3
    external: true
  log-1:
    name: elasticsearch-log-1
    external: true
  log-2:
    name: elasticsearch-log-2
    external: true
  log-3:
    name: elasticsearch-log-3
    external: true
